company:
  name: Maples Group
  sender_name: Hamza
  sender_title: Analyst
csv_columns:
  amount: Amount
  attachment: Attachment Path
  bcc: BCC
  cc: CC
  custom_message: Custom Message
  due_date: Due Date
  email_type: Email Type
  entity_name: Entity Name
  group: Group
  invoice_number: Invoice Number
  link: Link
  subject: Subject
  to: To
email:
  format: auto
  from: hamzanabiel@gmail.com
  subject_followup: 'Follow Up: {entity_name} Invoice {invoice_number}'
  subject_group: '{group_name} Invoices {invoice_numbers}'
  subject_single: '{entity_name} Invoice {invoice_number}'
grouping:
  entity_column: Entity Name
  group_column: Group
  invoice_column: Invoice Number
logging:
  console: true
  file: email_tool.log
  level: INFO
output:
  filename_pattern: '{entity}_{invoice}_{timestamp}'
  organize_by_date: false
  timestamp: true
paths:
  attachment_base: /Users/hamza/Documents/GitHub/zzinvoices
  banner: config/banner.png
  output: output
  template: config/template.html
  template_followup: config/template_followup.html
validation:
  check_attachments: true
  validate_emails: true
  warn_missing_fields: true
